name: Stock Scanner Auto Run

on:
  schedule:
    # 00:05 (09:05 KST), 01:25 (10:25 KST), 04:25 (13:25 KST), 06:05 (15:05 KST)
    - cron: '3 0 * * 1-5'
    - cron: '22 1 * * 1-5'
    - cron: '07 4 * * 1-5'
    - cron: '2 6 * * 1-5'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run All Scanners
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PYTHONIOENCODING: "utf-8"
          TZ: "Asia/Seoul" # 시스템 타임존을 한국으로 설정
          GITHUB_EVENT_NAME: ${{ github.event_name }} # 필수!
        run: |
          python alert.py
          python alert_value.py
